export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_GET = 'AUTH_LOGIN_USER_GET';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const PLAYER_PLAY_MUSIC = 'PLAYER_PLAY_MUSIC';
export const PLAYER_PAUSE_MUSIC = 'PLAYER_PAUSE_MUSIC';
export const PLAYER_RELEASE_MUSIC = 'PLAYER_RELEASE_MUSIC';

export const PLAYER_LISTEN_MUSIC = 'PLAYER_LISTEN_MUSIC';
export const PLAYER_UNLISTEN_MUSIC = 'PLAYER_UNLISTEN_MUSIC';

export const PLAYER_COMMON_MUSIC = 'PLAYER_COMMON_MUSIC';
export const PLAYER_RANDOM_MUSIC = 'PLAYER_RANDOM_MUSIC';

export const PLAYER_UNREPEAT_MUSIC = 'PLAYER_UNREPEAT_MUSIC';
export const PLAYER_REPEAT_MUSIC = 'PLAYER_REPEAT_MUSIC';
export const PLAYER_REPEAT_ONE_MUSIC = 'PLAYER_REPEAT_ONE_MUSIC';

export const PLAYER_LIKE_MUSIC = 'PLAYER_LIKE_MUSIC';
export const PLAYER_UNLIKE_MUSIC = 'PLAYER_UNLIKE_MUSIC';

export const PLAYER_CREATE_PREVIOUS = 'PLAYER_CREATE_PREVIOUS';
export const PLAYER_ADD_TRACK_PREVIOUS = 'PLAYER_ADD_TRACK_PREVIOUS';
export const PLAYER_LIKE_TRACK_PREVIOUS = 'PLAYER_LIKE_TRACK_PREVIOUS';
export const PLAYER_UNLIKE_TRACK_PREVIOUS = 'PLAYER_UNLIKE_TRACK_PREVIOUS';
export const PLAYER_ADD_BEGIN_PREVIOUS = 'PLAYER_ADD_BEGIN_PREVIOUS';
export const PLAYER_DELETE_PREVIOUS = 'PLAYER_DELETE_PREVIOUS';
export const PLAYER_CLEAR_PREVIOUS = 'PLAYER_CLEAR_PREVIOUS';

export const PLAYER_ADD_CURRENT_TRACK = 'PLAYER_ADD_CURRENT_TRACK';
export const PLAYER_LIKE_CURRENT_TRACK = 'PLAYER_LIKE_CURRENT_TRACK';
export const PLAYER_UNLIKE_CURRENT_TRACK = 'PLAYER_UNLIKE_CURRENT_TRACK';

export const PLAYER_CREATE_QUEUE = 'PLAYER_CREATE_QUEUE';
export const PLAYER_ADD_EDITION_QUEUE = 'PLAYER_ADD_EDITION_QUEUE';
export const PLAYER_ADD_TRACK_QUEUE = 'PLAYER_ADD_TRACK_QUEUE';
export const PLAYER_LIKE_TRACK_QUEUE = 'PLAYER_LIKE_TRACK_QUEUE';
export const PLAYER_UNLIKE_TRACK_QUEUE = 'PLAYER_UNLIKE_TRACK_QUEUE';
export const PLAYER_ADD_BEGIN_QUEUE = 'PLAYER_ADD_BEGIN_QUEUE';
export const PLAYER_CHANGE_QUEUE = 'PLAYER_CHANGE_QUEUE';
export const PLAYER_DELETE_QUEUE = 'PLAYER_DELETE_QUEUE';
export const PLAYER_REMOVE_QUEUE = 'PLAYER_REMOVE_QUEUE';
export const PLAYER_CLEAR_QUEUE = 'PLAYER_CLEAR_QUEUE';

export const PLAYER_CREATE_PLAYLIST = 'PLAYER_CREATE_PLAYLIST';
export const PLAYER_ADD_EDITION_PLAYLIST = 'PLAYER_ADD_EDITION_PLAYLIST';
export const PLAYER_ADD_TRACK_PLAYLIST = 'PLAYER_ADD_TRACK_PLAYLIST';
export const PLAYER_LIKE_TRACK_PLAYLIST = 'PLAYER_LIKE_TRACK_PLAYLIST';
export const PLAYER_UNLIKE_TRACK_PLAYLIST = 'PLAYER_UNLIKE_TRACK_PLAYLIST';
export const PLAYER_REMOVE_PLAYLIST = 'PLAYER_REMOVE_PLAYLIST';
export const PLAYER_CLEAR_PLAYLIST = 'PLAYER_CLEAR_PLAYLIST';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const FETCH_PERFORMER_SUCCESS = 'FETCH_PERFORMER_SUCCESS';
export const FETCH_PERFORMER_FAIL = 'FETCH_PERFORMER_FAIL';

export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';

export const FETCH_EDITION_SUCCESS = 'FETCH_EDITION_SUCCESS';
export const FETCH_EDITION_FAIL = 'FETCH_EDITION_FAIL';
export const EDITION_INFO_CLEAR = 'EDITION_INFO_CLEAR';
export const EDITION_ADD_LIKE = 'EDITION_ADD_LIKE';
export const EDITION_DELETE_LIKE = 'EDITION_DELETE_LIKE';
export const TRACK_ADD_LIKE = 'TRACK_ADD_LIKE';
export const TRACK_DELETE_LIKE = 'TRACK_DELETE_LIKE';
export const TRACK_INCREMENT_LISTENING = 'TRACK_INCREMENT_LISTENING';
