export const PLAYER_PLAY_MUSIC = 'PLAYER_PLAY_MUSIC';
export const PLAYER_PAUSE_MUSIC = 'PLAYER_PAUSE_MUSIC';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const FETCH_EDITION_CLEAR = 'FETCH_EDITION_CLEAR';
export const FETCH_EDITION_SUCCESS = 'FETCH_EDITION_SUCCESS';
export const FETCH_EDITION_FAIL = 'FETCH_EDITION_FAIL';
