export const PLAYER_PLAY_MUSIC = 'PLAYER_PLAY_MUSIC';
export const PLAYER_PAUSE_MUSIC = 'PLAYER_PAUSE_MUSIC';
export const PLAYER_RELEASE_MUSIC = 'PLAYER_RELEASE_MUSIC';

export const PLAYER_COMMON_MUSIC = 'PLAYER_COMMON_MUSIC';
export const PLAYER_RANDOM_MUSIC = 'PLAYER_RANDOM_MUSIC';

export const PLAYER_UNREPEAT_MUSIC = 'PLAYER_UNREPEAT_MUSIC';
export const PLAYER_REPEAT_MUSIC = 'PLAYER_REPEAT_MUSIC';
export const PLAYER_REPEAT_ONE_MUSIC = 'PLAYER_REPEAT_ONE_MUSIC';

export const PLAYER_LIKE_MUSIC = 'PLAYER_LIKE_MUSIC';
export const PLAYER_UNLIKE_MUSIC = 'PLAYER_UNLIKE_MUSIC';

export const PLAYER_CREATE_PREVIOUS = 'PLAYER_CREATE_PREVIOUS';
export const PLAYER_ADD_TRACK_PREVIOUS = 'PLAYER_ADD_TRACK_PREVIOUS';
export const PLAYER_DELETE_PREVIOUS = 'PLAYER_DELETE_PREVIOUS';

export const PLAYER_CREATE_PREVIOUS_RANDOM = 'PLAYER_CREATE_PREVIOUS_RANDOM';
export const PLAYER_ADD_TRACK_PREVIOUS_RANDOM = 'PLAYER_ADD_TRACK_PREVIOUS_RANDOM';
export const PLAYER_DELETE_PREVIOUS_RANDOM = 'PLAYER_DELETE_PREVIOUS_RANDOM';

export const PLAYER_ADD_CURRENT_TRACK = 'PLAYER_ADD_CURRENT_TRACK';

export const PLAYER_CREATE_QUEUE = 'PLAYER_CREATE_QUEUE';
export const PLAYER_ADD_EDITION_QUEUE = 'PLAYER_ADD_EDITION_QUEUE';
export const PLAYER_ADD_TRACK_QUEUE = 'PLAYER_ADD_TRACK_QUEUE';
export const PLAYER_ADD_BEGIN_QUEUE = 'PLAYER_ADD_BEGIN_QUEUE';
export const PLAYER_CHANGE_QUEUE = 'PLAYER_CHANGE_QUEUE';
export const PLAYER_DELETE_QUEUE = 'PLAYER_DELETE_QUEUE';
export const PLAYER_REMOVE_QUEUE = 'PLAYER_REMOVE_QUEUE';

export const PLAYER_CREATE_QUEUE_RANDOM = 'PLAYER_CREATE_QUEUE_RANDOM';
export const PLAYER_ADD_EDITION_QUEUE_RANDOM = 'PLAYER_ADD_EDITION_QUEUE_RANDOM';
export const PLAYER_ADD_TRACK_QUEUE_RANDOM = 'PLAYER_ADD_TRACK_QUEUE_RANDOM';
export const PLAYER_ADD_BEGIN_QUEUE_RANDOM = 'PLAYER_ADD_BEGIN_QUEUE_RANDOM';
export const PLAYER_CHANGE_QUEUE_RANDOM = 'PLAYER_CHANGE_QUEUE_RANDOM';
export const PLAYER_DELETE_QUEUE_RANDOM = 'PLAYER_DELETE_QUEUE_RANDOM';
export const PLAYER_REMOVE_QUEUE_RANDOM = 'PLAYER_REMOVE_QUEUE_RANDOM';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const FETCH_EDITION_CLEAR = 'FETCH_EDITION_CLEAR';
export const FETCH_EDITION_SUCCESS = 'FETCH_EDITION_SUCCESS';
export const FETCH_EDITION_FAIL = 'FETCH_EDITION_FAIL';
